"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def gen_fibonacci(a):
	x = 0
	while x < a:
		x = fibonacci[-2] + fibonacci[-1]
		fibonacci.append(x)

def select_evens(b):
	for i in b:
		if i % 2 == 0:
			even_fibs.append(i)

def solution(x):
	gen_fibonacci(x)
	select_evens(fibonacci)
	print(sum(even_fibs))

fibonacci = [1,2]
even_fibs = []
solution(4000000)